# Generated by Django 4.0.2 on 2022-07-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0003_alter_profile_agree_with_site_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Agree_with_site_rule',
            new_name='user_flag',
        ),
    ]
