# Generated by Django 4.0.2 on 2022-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0004_rename_agree_with_site_rule_profile_user_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_profile',
            name='clubs_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='univer_profile',
            name='univer_flag',
            field=models.BooleanField(default=False),
        ),
    ]
