# Generated by Django 4.0.2 on 2022-07-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0005_club_profile_clubs_flag_univer_profile_univer_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_profile',
            old_name='clubs_flag',
            new_name='flag',
        ),
        migrations.RenameField(
            model_name='univer_profile',
            old_name='univer_flag',
            new_name='flag',
        ),
    ]
