# Generated by Django 4.0.2 on 2022-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0006_rename_clubs_flag_club_profile_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telega',
            field=models.CharField(default='', max_length=50),
        ),
    ]
