# Generated by Django 4.0.2 on 2022-08-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0010_club_profile_is_cl_univer_profile_is_un'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Position_for_Un',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TeamedUp.univer_profile')),
            ],
        ),
    ]
