# Generated by Django 4.0.2 on 2022-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0012_open_position_for_un_sport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open_position_for_un',
            old_name='Sport',
            new_name='position',
        ),
        migrations.AddField(
            model_name='open_position_for_un',
            name='grant',
            field=models.CharField(choices=[('F', 'Full'), ('NF', 'Not full'), ('N', 'None')], default='----', max_length=15),
        ),
        migrations.AddField(
            model_name='open_position_for_un',
            name='sport_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
