# Generated by Django 4.0.2 on 2022-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0013_rename_sport_open_position_for_un_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_profile',
            name='club_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='club_profile',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='univer_profile',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='univer_profile',
            name='univers_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
