# Generated by Django 4.0.2 on 2022-08-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0014_club_profile_club_name_club_profile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Position_for_Cl',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TeamedUp.univer_profile')),
                ('active', models.BooleanField(default=True)),
                ('sport_name', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
