# Generated by Django 4.0.2 on 2022-08-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0015_open_position_for_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position_for_cl',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TeamedUp.club_profile'),
        ),
    ]
