# Generated by Django 4.0.2 on 2022-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0016_alter_open_position_for_cl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer_profile',
            name='count_pos',
            field=models.IntegerField(default=0),
        ),
    ]
