# Generated by Django 4.0.2 on 2022-08-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0024_alter_open_position_for_un_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_position_for_un',
            name='name',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, primary_key=0, to='TeamedUp.univer_profile', unique=0),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='open_position_for_un',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
