# Generated by Django 4.0.2 on 2022-08-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0025_open_position_for_un_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open_position_for_un',
            old_name='name',
            new_name='owner',
        ),
    ]
