# Generated by Django 4.0.2 on 2022-08-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0027_open_position_for_cl_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position_for_cl',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='open_position_for_un',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
    ]
