# Generated by Django 4.0.2 on 2022-08-17 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamedUp', '0028_alter_open_position_for_cl_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position_for_un',
            name='grant',
            field=models.CharField(choices=[('Full', 'Full'), ('Not full', 'Not full'), ('None', 'None')], default='----', max_length=15),
        ),
        migrations.CreateModel(
            name='small_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
