# Generated by Django 4.0.2 on 2022-08-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0029_alter_open_position_for_un_grant_small_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivment',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('owner', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, primary_key=0, to='TeamedUp.profile', unique=0)),
            ],
        ),
    ]
