# Generated by Django 4.0.2 on 2022-08-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0031_alter_profile_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telega',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
