# Generated by Django 4.0.2 on 2022-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0032_alter_profile_telega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Height_inch_and_cm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Weight_pound_and_kg',
        ),
        migrations.AddField(
            model_name='profile',
            name='act',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_courses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='agree_to_private_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eng_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inch',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ielts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='live_stream_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='math_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='natural_science_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_science',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='stats_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='toefl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='university_or_club',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_pound',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
