# Generated by Django 4.0.2 on 2022-08-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0033_remove_profile_height_inch_and_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Languages',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField()),
                ('owner', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, primary_key=0, to='TeamedUp.profile', unique=0)),
            ],
        ),
    ]
