# Generated by Django 4.0.2 on 2022-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0035_open_position_for_cl_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='letter',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
