# Generated by Django 4.0.2 on 2022-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0038_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_position_for_cl',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='open_position_for_un',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
