# Generated by Django 4.0.2 on 2022-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0039_open_position_for_cl_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_languages',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
