# Generated by Django 4.0.2 on 2022-08-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0040_alter_extra_languages_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_languages',
            name='owner',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='TeamedUp.profile', unique=0),
        ),
    ]
