# Generated by Django 4.0.2 on 2022-08-29 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TeamedUp', '0041_alter_extra_languages_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('phone_num', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('first_language', models.CharField(blank=True, max_length=100)),
                ('second_language', models.CharField(blank=True, max_length=100)),
                ('third_language', models.CharField(max_length=100)),
                ('whats_app', models.BooleanField(blank=True, default=True)),
                ('telega', models.CharField(blank=True, default='', max_length=50)),
                ('zoom', models.CharField(blank=True, default='', max_length=50)),
                ('discord', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
