# Generated by Django 4.0.2 on 2022-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0042_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_teem',
            field=models.BooleanField(default=False),
        ),
    ]
