# Generated by Django 4.0.2 on 2022-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0043_profile_national_teem'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='achivment',
            name='title_of_achiv',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='achivment',
            name='type',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='tutor',
            name='about_me',
            field=models.CharField(default='', max_length=500),
        ),
    ]
