# Generated by Django 4.0.2 on 2022-08-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0045_teems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teems',
            new_name='Teem',
        ),
    ]
