# Generated by Django 4.0.2 on 2022-08-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0046_rename_teems_teem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teem',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teem',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
