# Generated by Django 4.0.2 on 2022-08-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0048_alter_open_position_for_un_grant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_profile',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
