# Generated by Django 4.0.2 on 2022-08-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0049_alter_univer_profile_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univer_profile',
            old_name='flag',
            new_name='second_active',
        ),
    ]
