# Generated by Django 4.0.2 on 2022-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0050_rename_flag_univer_profile_second_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univer_profile',
            old_name='second_active',
            new_name='flag',
        ),
    ]
