# Generated by Django 4.0.2 on 2022-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0051_rename_second_active_univer_profile_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_profile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='univer_profile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
