# Generated by Django 4.0.2 on 2022-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0052_club_profile_country_univer_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_position_for_un',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
