# Generated by Django 4.0.2 on 2022-09-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0053_open_position_for_un_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_position_for_un',
            name='flag',
        ),
    ]
