# Generated by Django 4.0.2 on 2022-09-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0054_remove_open_position_for_un_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position_for_un',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
