# Generated by Django 4.0.2 on 2022-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0055_alter_open_position_for_un_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivment',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extra_languages',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teem',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
