# Generated by Django 4.0.2 on 2022-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0057_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ex',
            field=models.IntegerField(default=0),
        ),
    ]
