# Generated by Django 4.0.2 on 2022-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0058_profile_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_position_for_un',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='open_position_for_un',
            name='teem_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
