# Generated by Django 4.0.2 on 2022-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0061_alter_open_position_for_un_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position_for_un',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
