# Generated by Django 4.0.2 on 2022-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0062_alter_open_position_for_un_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_position_for_un',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
