# Generated by Django 4.1.7 on 2023-03-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0063_alter_open_position_for_un_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whats_app',
        ),
        migrations.AddField(
            model_name='profile',
            name='main_achivment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
