# Generated by Django 4.1.7 on 2023-03-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0064_remove_profile_phone_num_remove_profile_whats_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
