# Generated by Django 4.1.7 on 2023-03-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0065_remove_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='small_admin',
        ),
    ]
