# Generated by Django 4.1.7 on 2023-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0067_small_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biscuits',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
