# Generated by Django 4.1.7 on 2023-03-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0068_profile_biscuits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biscuits',
        ),
    ]
